# Generated by Django 4.0.5 on 2022-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busname', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('nbrsieges', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=2)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
            ],
        ),
    ]
