# Generated by Django 4.1 on 2022-08-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('date_entree', models.DateField()),
                ('quantite_entree', models.CharField(max_length=30)),
                ('date_sortie', models.DateField()),
                ('quantite_sortie', models.CharField(max_length=30)),
                ('stock_initial', models.CharField(max_length=30)),
                ('stock_reel', models.CharField(max_length=30)),
                ('stock_provisionnel', models.CharField(max_length=30)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.CharField(max_length=30)),
                ('observation', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='bus',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.AddField(
            model_name='reservation',
            name='toner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.toner'),
            preserve_default=False,
        ),
    ]
